### PR TITLE
Bubble up scalar error

### LINKED ISSUE #427: Literal Scalar Parsing should not panic
**Describe the bug**
Literal Scalar Parsing should not panic. Sending badly shaped data is a thing that Denial-Of-Service attackers like to do -- and being able to panic the thread this easy is a smell in my opinion.

**To Reproduce**
1. Define a schema with a scalar String, Int, or Float type
2. Query the schema with query literals which violate the contract in step (1)
3. Notice that the thread panics
4. Code reference here: https://github.com/graphql-rust/juniper/blob/master/juniper/src/parser/value.rs ... look for `parse_scalar_literal_by_infered_type` and then look for the panics.

**Expected behavior**
The framework should handle this class of error gracefully without a panic. It should return in this case a proper `400 Bad Request` HTTP Response with the standard graphql json error reporting array format: `{ "errors": [ "... must be an Int" ] }`

**Additional context**
Violating the api shape is one of the easiest things a would-be denial-of-service attacker can try to attempt to crash your service and/or waste cpu cycles/compute resources/network resources.

### PR DESCRIPTION
**Pull request by andy128k**
Closes #427

### CODE REVIEW

**Comment by LegNeato** [comment]
Awesome, thank you so much for the PR! Can you add a test exercising this so we don't regress in the future?

**Comment by andy128k** [comment]
@LegNeato  I am trying to reproduce issue #427 but I cannot. :(

**Comment by LegNeato** [comment]
@dreamcodez any help here?

**Comment by dreamcodez** [comment]
I am not sure what this 'In disguise' business is. really all you need is this:
```
impl Query {
    fn get_int(value: i32) -> i32 { value }
}
```
and then send a string instead of an integer for the value as a quoted literal.

**Comment by dreamcodez** [comment]
I wanted to isolated but due to private restrictions i would have to dig deeper than I have time for right now, here is where I left off:


```
Last login: Fri Oct 11 13:48:20 on ttys001
Matts-MacBook-Pro:~ matt$ cd juni
Matts-MacBook-Pro:~ matt$ ls
Applications			Library
BIRTHDAY_JESSICA		Movies
CLUTTER				Music
Desktop				Pictures
Documents			Public
Downloads			VirtualBox VMs
GETTEXT				bin
GITLAB				dev
Google Drive File Stream
Matts-MacBook-Pro:~ matt$ cd dev
Matts-MacBook-Pro:dev matt$ ls
endpoint
Matts-MacBook-Pro:dev matt$ cd
Matts-MacBook-Pro:dev matt$ ls
endpoint
Matts-MacBook-Pro:dev matt$ mkdir juniper-example
Matts-MacBook-Pro:dev matt$ mv juniper-issue-427
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
Matts-MacBook-Pro:dev matt$ mkdir juniper-is
Matts-MacBook-Pro:dev matt$ mv juniper-example juniper-issue-427
Matts-MacBook-Pro:dev matt$ cd juniper-issue-427/
Matts-MacBook-Pro:juniper-issue-427 matt$ ls
Matts-MacBook-Pro:juniper-issue-427 matt$ ls
Matts-MacBook-Pro:juniper-issue-427 matt$ cargo init .
-bash: cargo: command not found
Matts-MacBook-Pro:juniper-issue-427 matt$ cargo
-bash: cargo: command not found
Matts-MacBook-Pro:juniper-issue-427 matt$ rust
-bash: rust: command not found
Matts-MacBook-Pro:juniper-issue-427 matt$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

info: downloading installer

Welcome to Rust!

This will download and install the official compiler for the Rust
programming language, and its package manager, Cargo.

It will add the cargo, rustc, rustup and other commands to
Cargo's bin directory, located at:

  /Users/matt/.cargo/bin

This can be modified with the CARGO_HOME environment variable.

Rustup metadata and toolchains will be installed into the Rustup
home directory, located at:

  /Users/matt/.rustup

This can be modified with the RUSTUP_HOME environment variable.

This path will then be added to your PATH environment variable by
modifying the profile file located at:

  /Users/matt/.profile

You can uninstall at any time with rustup self uninstall and
these changes will be reverted.

Current installation options:


   default host triple: x86_64-apple-darwin
     default toolchain: stable
               profile: default
  modify PATH variable: yes

1) Proceed with installation (default)
2) Customize installation
3) Cancel installation
>
info: profile set to 'default'
[package]
info: syncing channel updates for 'stable-x86_64-apple-darwin'
info: latest update on 2019-09-26, rust version 1.38.0 (625451e37 2019-09-23)
info: downloading component 'cargo'
  3.7 MiB /   3.7 MiB (100 %) 915.7 KiB/s in  4s ETA:  0s
info: downloading component 'clippy'
  1.3 MiB /   1.3 MiB (100 %) 895.3 KiB/s in  1s ETA:  0s
info: downloading component 'rust-docs'
 11.7 MiB /  11.7 MiB (100 %)   1.3 MiB/s in  9s ETA:  0s
info: downloading component 'rust-std'
170.9 MiB / 170.9 MiB (100 %)   1.3 MiB/s in  2m 19s ETA:  0s
info: downloading component 'rustc'
[package]
 60.4 MiB /  60.4 MiB (100 %)   1.2 MiB/s in 47s ETA:  0s
info: downloading component 'rustfmt'
  1.9 MiB /   1.9 MiB (100 %)   1.4 MiB/s in  1s ETA:  0s
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
 11.7 MiB /  11.7 MiB (100 %)   8.3 MiB/s in  1s ETA:  0s
info: installing component 'rust-std'
170.9 MiB / 170.9 MiB (100 %)  33.4 MiB/s in  5s ETA:  0s
info: installing component 'rustc'
 60.4 MiB /  60.4 MiB (100 %)  15.1 MiB/s in  4s ETA:  0s
info: installing component 'rustfmt'
info: default toolchain set to 'stable'

  stable installed - rustc 1.38.0 (625451e37 2019-09-23)


~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
"src/main.rs" 5L, 82C written
use juniper::parser::parse_literal_value;

fn main() {
  parse_literal_value();
}
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
use juniper::{EmptyMutation};
use juniper::parser::parse_document_source;
use juniper::{EmptyMutation};
use juniper::parser::parse_document_source;
use juniper::parser::document::SchemaType;

struct Query;

#[juniper::object]
impl Query {
    fn get_int(value: i32) -> i32 { value }
}

fn issue_427_panic_is_expected_for_int_scalar() {
    let schema = SchemaType::new::<Query, EmptyMutation<()>>(&(), &());

    let parse_result = parse_document_source(r##"{ getInt(value: "123") }"##, &schema);

    println!("{:#?}", parse_result.unwrap());
}

fn main() {
  issue_427_panic_is_expected_for_int_scalar()
}
```

```
Matts-MacBook-Pro:juniper-issue-427 matt$ cargo run
   Compiling juniper-issue-427 v0.1.0 (/Users/matt/dev/juniper-issue-427)
error[E0603]: module `document` is private
 --> src/main.rs:3:22
  |
3 | use juniper::parser::document::SchemaType;
  |                      ^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0603`.
error: Could not compile `juniper-issue-427`.

```

**Comment by dreamcodez** [comment]
@andy128k made a bounty on related issue 427 : https://www.bountysource.com/issues/80699749-literal-scalar-parsing-should-not-panic

**Comment by theduke** [comment]
Sorry for the delay.

I'm fixing up the code a bit, adding some tests a bit and will merge in an hour or so.

**Comment by theduke** [comment]
Please see the issue.

We need a proper reproduction first.

File: juniper/src/parser/tests/document.rs [hunk 1]
```diff
@@ -145,3 +146,20 @@ fn errors() {
...
+    impl QueryWithoutFloat {
+        fn get_int(value: String) -> String {
+            value
+        }
+    }
+
+    let schema = SchemaType::new::<QueryWithoutFloat, EmptyMutation<()>>(&(), &());
+    let parse_result = parse_document_source(r##"{ getInt(value: 123.0) }"##, &schema);
+
+    assert!(parse_result.is_err());
```
Comment (LegNeato) [inline juniper/src/parser/tests/document.rs]: We should check that it is an `ExpectedScalarError` rather than just check for any error to prevent shadowing a possible underlying bug.

Comment (andy128k) [reply juniper/src/parser/tests/document.rs]: Done

**Comment by LegNeato** [comment]
Thanks so much for the PR 🍻 . Sorry it took so long to merge! Any bounty should be worked out between @dreamcodez and @andy128k.

**Comment by LegNeato** [comment]
I pushed a point release with this fix in it 🎉
