### PR TITLE
Fix fields on interface not being resolved when used with fragments

### LINKED ISSUE #922: Fields on interface fragment spreads don't get resolved
**Describe the bug**

When resolving fields defined on an interface, if the field is defined within a fragment spread, then it is omitted from the output.

I'm happy to work on a fix for this, but will need some guidance on where to look (and whatever other tips/hints you could give me).

**To Reproduce**

Using the schema defined in `juniper/src/tests/fixtures/starwars/` (I ran the `juniper_rocket_async` example to reproduce):

### Working

A simple query returns the expected result (`id` and `name` fields are populated).

```graphql
query {
  hero {
    id
    name
  }
}
```

```json
{
  "data": {
    "hero": {
      "id": "2001",
      "name": "R2-D2"
    }
  }
}
```

### Broken

But this query, using a fragment spread on the `Character` interface, is broken (`id` and `name` fields are omitted in the response):

```graphql
{
  hero {
    ... on Character {
      id
      name
    }
  }
}
```

```json
{
  "data": {
    "hero": {}
  }
}
```

**Expected behavior**

The second query above should return the exact same output as the first query.

**Additional context**

I encountered this problem using Relay in my UI, as parts of the query being generated by Relay use this pattern. Which leads me to believe that these queries should definitely be valid.

### PR DESCRIPTION
**Pull request by ArsileLuci**
Closes #922 

PR Checklist

 - [x] Ensure proper formatting
 - [x] Run all tests
 - [x] Update the CHANGELOG

### CODE REVIEW

File: juniper/src/types/async_await.rs [hunk 1]
```diff
@@ -306,7 +306,11 @@ where
                 );
 
                 let concrete_type_name = instance.concrete_type_name(sub_exec.context(), info);
-                if fragment.type_condition.item == concrete_type_name {
+                let type_name = instance.type_name(info);
+
+                if fragment.type_condition.item == concrete_type_name
+                    || Some(fragment.type_condition.item) == type_name
+                {
```
Comment (tyranron) [inline juniper/src/types/async_await.rs:312]: @ArsileLuci you've considered async resolving only. We need to consider sync resolving too.

File: integration_tests/juniper_tests/src/issue_922.rs [hunk 2]
```diff
@@ -0,0 +1,121 @@
...
+        for obj in values {
+            if let juniper::Value::Object(obj) = obj {
+                assert!(obj.contains_field("id"), "id field should be present");
+                assert!(obj.contains_field("name"), "name field should be present");
+            } else {
+                assert!(false, "List should contain value");
+            }
+        }
+    } else {
+        assert!(false, "List should be returned")
```
Comment (tyranron) [inline integration_tests/juniper_tests/src/issue_922.rs:118]: That's somewhat ackward assertions. We can do better by using `graphql_value!` macro. See integration tests for interfaces, for example.

File: integration_tests/juniper_tests/src/issue_922.rs [hunk 3]
```diff
@@ -0,0 +1,121 @@
+use juniper::*;
+
+struct Query;
+
+#[juniper::graphql_object]
+impl Query {
+    fn characters(executor: &Executor) -> Vec<CharacterValue> {
+        executor.look_ahead();
```
Comment (tyranron) [inline integration_tests/juniper_tests/src/issue_922.rs:8]: @ArsileLuci why do we need `executor` here? Does it influence test somehow? Remove it, if it's unnecessary.

File: integration_tests/juniper_tests/src/issue_922.rs [hunk 4]
```diff
@@ -0,0 +1,121 @@
...
+                name
+            }
+            ... on Droid {
+                id
+                name
+            }
+        }
+    "#;
+
+    let (res, errors) = juniper::execute(
```
Comment (tyranron) [inline integration_tests/juniper_tests/src/issue_922.rs:89]: @ArsileLuci consider to cover both `execute` (async) and `execute_sync` in tests.

**Review by tyranron — CHANGES_REQUESTED** [review]
Thanks! But some improvements are required.

**Review by tyranron — APPROVED** [review]
@ArsileLuci GJ, thanks! 🍻
